# Generated by Django 5.1.7 on 2025-04-08 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authSys', '0006_digicode'),
    ]

    operations = [
        migrations.CreateModel(
            name='uuidCode',
            fields=[
                ('id_member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('code_uuid', models.CharField(max_length=250, unique=True)),
                ('expiration_datetime', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='digiCode',
        ),
    ]
